version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_SQLITE_FILE: '/data/database.sqlite'
      DISABLE_IPV6: 'true'
    volumes:
      # For AX9000, please use "/mnt/docker_disk/mi_docker/nginxproxymanager/data:/data/db"
      - ./data:/data
      # For AX9000, please use "/mnt/docker_disk/mi_docker/nginxproxymanager/letsencrypt:/data/db"
      - ./letsencrypt:/etc/letsencrypt
      # For AX9000, please use "/mnt/docker_disk/mi_docker/nginxproxymanager/config.json:/app/config/production.json"
      - ./config.json:/app/config/production.json
